import = ["/home/jaskaran/.config/alacritty/alacritty-master/dracula.toml"]
[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
opacity = 0.7
blur= false

[font]
normal = { family = "Jetbrainsmono Nerd Font"}
